const { withPodfile, withXcodeProject } = require('expo/config-plugins')

// Two warnings the stock Expo iOS template leaves behind on every build. Both
// are cosmetic — neither changes what gets built — but they are the only noise
// in an otherwise clean `expo run:ios`, so they hide real warnings when one
// shows up. ios/ is gitignored and regenerated by prebuild, so the fixes have
// to live here rather than in the native project.

// 1. `ld: warning: ignoring duplicate libraries: '-lc++'`
//
// Pods-Wolffish.{debug,release}.xcconfig already ends OTHER_LDFLAGS with
// `-ObjC -l"c++"`, and that xcconfig is the app target's base configuration.
// The template then adds `$(inherited)` PLUS its own `-ObjC` and `-lc++`, so
// libc++ reaches the linker twice and ld warns. Dropping the target-level copy
// leaves the inherited one, which is what actually gets linked either way.
const withoutDuplicateLibcxx = (config) =>
  withXcodeProject(config, (cfg) => {
    const buildConfigurations = cfg.modResults.pbxXCBuildConfigurationSection()

    for (const key of Object.keys(buildConfigurations)) {
      // The section interleaves `<uuid>` objects with `<uuid>_comment` strings.
      const buildSettings = buildConfigurations[key]?.buildSettings
      const flags = buildSettings?.OTHER_LDFLAGS
      if (!Array.isArray(flags)) continue

      // Values keep their pbxproj quoting, i.e. the literal `"-lc++"`.
      buildSettings.OTHER_LDFLAGS = flags.filter(
        (flag) => String(flag).replace(/"/g, '').trim() !== '-lc++'
      )
    }

    return cfg
  })

// 2. `warning: Run script build phase '…' will be run during every build
//     because it does not specify any outputs.`
//
// Fifteen of the Pods project's shell script phases declare no outputs;
// thirteen of them already set alwaysOutOfDate, which is how Xcode is told
// "running every build is the point, stop asking for outputs". expo-updates'
// resource phase and Hermes' configuration-switch phase are the two upstream
// missed. Setting the same flag on them is not a behavior change — a phase
// with no outputs already runs every build — it only silences the warning.
// The hook is written to cover any phase in the same state so a future pod
// with the same omission does not reintroduce the noise.
const QUIET_SCRIPT_PHASES = `
    # Added by plugins/withQuietIosBuild.js — see the comments there.
    installer.pods_project.targets.each do |pod_target|
      pod_target.build_phases.each do |phase|
        next unless phase.is_a?(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
        next unless (phase.output_paths || []).empty?
        next unless (phase.output_file_list_paths || []).empty?
        phase.always_out_of_date = '1'
      end
    end
`

const withQuietPodScriptPhases = (config) =>
  withPodfile(config, (cfg) => {
    const contents = cfg.modResults.contents
    if (contents.includes('withQuietIosBuild.js')) return cfg

    // Expo's template opens exactly one post_install block, and the hook goes
    // at the top of it — ahead of react_native_post_install, whose own phase
    // edits all declare outputs, so nothing it adds later needs flagging. If
    // that ever stops holding, move this insertion after that call instead.
    const anchor = 'post_install do |installer|'
    const at = contents.indexOf(anchor)
    if (at === -1) {
      throw new Error(
        `[withQuietIosBuild] no "${anchor}" block in the Podfile — the template changed, update this plugin.`
      )
    }

    const insertAt = at + anchor.length
    cfg.modResults.contents =
      contents.slice(0, insertAt) + QUIET_SCRIPT_PHASES + contents.slice(insertAt)

    return cfg
  })

module.exports = (config) => withQuietPodScriptPhases(withoutDuplicateLibcxx(config))
